export const CHAT_ACTIONS = {

    SEND_MESSAGE: 'SEND_MESSAGE',
    CHANGE_USER: 'CHANGE_USER',
    CHANGE_RECEIVER:'CHANGE_RECEIVER',
    DELETE_MESSAGE:'DELETE_MESSAGE',
}

export const USER_REGISTER_ACTION = {

    ADD_USER: 'ADD_USER',

}